/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,jsx,ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        // Brand — matte black (numeric scale used by components: 50 … 900)
        primary: {
          DEFAULT: 'var(--color-primary-main)',
          50: '#f4f3f0',
          100: '#e6e4e0',
          200: '#cfccc6',
          300: '#a8a49b',
          400: '#7d7a73',
          500: '#55555c',
          600: '#3a3a40',
          700: '#222227',
          800: '#18181c',
          900: '#0a0a0b',
          dark: 'var(--color-primary-dark)',
          light: 'var(--color-primary-light)',
          contrast: 'var(--color-primary-contrast)',
        },
        // Accent — champagne gold
        secondary: {
          DEFAULT: 'var(--color-secondary-main)',
          50: '#faf6ec',
          100: '#f2e9d4',
          200: '#e7d3a3',
          300: '#dcc293',
          400: '#d4b478',
          500: 'var(--gold)',
          600: '#b8955c',
          700: '#a5834a',
          800: '#7d6338',
          900: '#5a4726',
          dark: 'var(--color-secondary-dark)',
          light: 'var(--color-secondary-light)',
          contrast: 'var(--color-secondary-contrast)',
        },
        accent: {
          DEFAULT: 'var(--color-accent-main)',
          50: '#faf6ec',
          100: '#f2e9d4',
          200: '#e7d3a3',
          300: '#dcc293',
          400: '#d4b478',
          500: 'var(--gold)',
          600: '#b8955c',
          700: '#a5834a',
          800: '#7d6338',
          900: '#5a4726',
          dark: 'var(--color-accent-dark)',
          light: 'var(--color-accent-light)',
          contrast: 'var(--color-accent-contrast)',
        },
        surface: {
          DEFAULT: 'var(--color-background-paper)',
          subtle: 'var(--color-background-subtle)',
          muted: 'var(--color-background-muted)',
        },
        neutral: {
          50: 'var(--color-neutral-50)',
          100: 'var(--color-neutral-100)',
          200: 'var(--color-neutral-200)',
          300: 'var(--color-neutral-300)',
          400: 'var(--color-neutral-400)',
          500: 'var(--color-neutral-500)',
          600: 'var(--color-neutral-600)',
          700: 'var(--color-neutral-700)',
          800: 'var(--color-neutral-800)',
          900: 'var(--color-neutral-900)',
        },
        // Semantic text (maps .text-primary / .text-secondary used across components)
        ink: {
          DEFAULT: 'var(--color-text-primary)',
          soft: 'var(--color-text-secondary)',
          hint: 'var(--color-text-hint)',
          disabled: 'var(--color-text-disabled)',
        },
        gold: {
          DEFAULT: 'var(--gold)',
          soft: 'var(--gold-soft)',
          deep: 'var(--gold-deep)',
        },
        success: { DEFAULT: 'var(--color-success-main)' },
        error: { DEFAULT: 'var(--color-error-main)' },
        warning: { DEFAULT: 'var(--color-warning-main)' },
        info: { DEFAULT: 'var(--color-info-main)' },
      },
      fontFamily: {
        sans: ['var(--font-sans)'],
        display: ['var(--font-display)'],
        // Aliases matching the naming used across components
        primary: ['var(--font-sans)'],
        secondary: ['var(--font-display)'],
        mono: ['var(--font-family-mono)'],
      },
      fontSize: {
        xs: 'var(--font-size-xs)',
        sm: 'var(--font-size-sm)',
        base: 'var(--font-size-base)',
        lg: 'var(--font-size-lg)',
        xl: 'var(--font-size-xl)',
        '2xl': 'var(--font-size-2xl)',
        '3xl': 'var(--font-size-3xl)',
        '4xl': 'var(--font-size-4xl)',
        '5xl': 'var(--font-size-5xl)',
        '6xl': 'var(--font-size-6xl)',
        '7xl': 'var(--font-size-7xl)',
      },
      borderRadius: {
        xs: 'var(--border-radius-xs)',
        sm: 'var(--border-radius-sm)',
        DEFAULT: 'var(--border-radius-md)',
        md: 'var(--border-radius-md)',
        lg: 'var(--border-radius-lg)',
        xl: 'var(--border-radius-xl)',
        '2xl': 'var(--border-radius-2xl)',
        '3xl': 'var(--border-radius-3xl)',
      },
      boxShadow: {
        xs: 'var(--shadow-xs)',
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        xl: 'var(--shadow-xl)',
        '2xl': 'var(--shadow-2xl)',
        inner: 'var(--shadow-inner)',
        gold: 'var(--glow-gold)',
      },
      backgroundImage: {
        'gradient-button': 'var(--gradient-button)',
        'gradient-gold': 'var(--gradient-gold)',
        'gradient-ink': 'var(--gradient-ink)',
        'gradient-ivory': 'var(--gradient-ivory)',
      },
      transitionTimingFunction: {
        smooth: 'var(--ease)',
        'ease-in-out': 'var(--ease-in-out)',
      },
      maxWidth: {
        container: 'var(--container)',
        'container-xl': 'var(--container-xl)',
      },
      zIndex: {
        header: 'var(--z-index-header)',
        popover: 'var(--z-index-popover)',
        drawer: 'var(--z-index-drawer)',
        modal: 'var(--z-index-modal)',
        toast: 'var(--z-index-toast)',
      },
      keyframes: {
        'fade-up': {
          '0%': { opacity: '0', transform: 'translateY(16px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        marquee: {
          '0%': { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(-50%)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '200% 0' },
          '100%': { backgroundPosition: '-200% 0' },
        },
      },
      animation: {
        'fade-up': 'fade-up 0.6s var(--ease) both',
        'fade-in': 'fade-in 0.4s var(--ease) both',
        marquee: 'marquee 30s linear infinite',
        shimmer: 'shimmer 1.6s linear infinite',
      },
    },
  },
  plugins: [],
}
